name: love_sync
description: "A new Flutter project."
publish_to: 'none'
version: 1.1.8

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  firebase_database: ^11.1.0
  shared_preferences: ^2.5.3
  google_fonts: ^6.3.3
  intl: ^0.20.2
  flutter_svg: ^2.2.3
  google_sign_in: ^6.2.1
  http: ^1.2.2
  package_info_plus: ^9.0.0
  dio: ^5.4.0             
  path_provider: ^2.1.2   
  permission_handler: ^11.3.0 
  open_file: ^3.5.10
  vibration: ^3.1.4
  firebase_storage: ^12.4.10
  image_picker: ^1.0.7
  cached_network_image: ^3.3.1

  flutter_localizations:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true
