name: love_sync
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  firebase_database: ^11.1.0
  shared_preferences: ^2.5.3
  google_fonts: ^6.3.3
  intl: ^0.20.2
  flutter_svg: ^2.2.3
  google_sign_in: ^6.2.1
  http: ^1.2.2
  package_info_plus: ^9.0.0
  r_upgrade: ^0.4.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
